# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8ac3ee1b0a53c1edc2b12ca27039b2840147e0d5322bf951f15480bd1a4935c44bfaca4db8ed7c9227e4926d01b8350dffbf31a7b780d7548ab43182ca3ea02

test:
  secret_key_base: d8d7d28df191736f203007c66c3727edcd89127710f96be640b1afdaea9ac6afa486cf3546339d03ff6ad0d798953167bebb70e47dfca46ed8f1729f49e4edc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
